using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Tests;

public class WorldDataSerialized
{

    public const string expectedSerialized = """
        # world new [baba] city
        ---- BEGIN WORLD ----
        AQAPAAAAbmV3IFtiYWJhXSBjaXR5
        ---- END WORLD ----

        # 0 autumnregion
        ---- BEGIN REGION ----
        AAACAAYAAABhdXR1bW4KAAAAZWRpdG9yc29uZwwAAABhdXR1bW5yZWdpb24=
        ---- END REGION ----

        # 1 region 2
        ---- BEGIN REGION ----
        AQADAAYAAABnYXJkZW4HAAAAZGVmYXVsdAgAAAByZWdpb24gMg==
        ---- END REGION ----

        # 2 new region 2
        ---- BEGIN REGION ----
        AgAEAAUAAABzd2FtcAcAAABkZWZhdWx0DAAAAG5ldyByZWdpb24gMg==
        ---- END REGION ----

        # 3 starting region
        ---- BEGIN REGION ----
        AwAFAAYAAABnYXJkZW4HAAAAZGVmYXVsdA8AAABzdGFydGluZyByZWdpb24=
        ---- END REGION ----

        # 1 global
        ---- BEGIN MAP ----
        KAAAAAAQAAAAAAAAAAAAAAAAASABIABgAAAGdsb2JhbA==iAAAAAACEAAAAAAAQA
        AAAFAAAAAAAAAAEAAAAAAAAAAAAABAAAAAADAAAAAAAFAAAABQAAAAAAAAABAAAA
        AAAAAAAAANsAAAAAIQAAAAAABgAAAAUAAAAAAAAAAQAAAAAAAAAAAAA3AQAA
        ---- END MAP ----

        # 2 region 0 - autumnregion
        ---- BEGIN MAP ----
        PAAAAAAgAAAAAAAAAAAAAAAAAKAAoAFwAAAHJlZ2lvbiAwIC0gYXV0dW1ucmVnaW
        9uXAAAAAADEAAAAAAAIAAAACAAAAAAAAAAAAAAAAAAAAAAAADQAAAAAxAAAAAAAF
        AAAABAAAAAAAAAAAAAAAAAAAAAAAAA0AAAA=
        ---- END MAP ----

        # 3 region 1 - region 2
        ---- BEGIN MAP ----
        OAAAAAAwAAAAAAAAAAAAAAAAASABIAEwAAAHJlZ2lvbiAxIC0gcmVnaW9uIDI=AA
        AAAA
        ---- END MAP ----

        # 4 region 2 - new region 2
        ---- BEGIN MAP ----
        PAAAAABAAAAAAAAAAAAAAAAAASABIAFwAAAHJlZ2lvbiAyIC0gbmV3IHJlZ2lvbi
        AyAAAAAA
        ---- END MAP ----

        # 5 region 3 - starting region
        ---- BEGIN MAP ----
        QAAAAABQAAAAAAAAAAAAAAAAAPAA8AGgAAAHJlZ2lvbiAzIC0gc3RhcnRpbmcgcm
        VnaW9uAAAAAA
        ---- END MAP ----

        # 7 6 uplayer - start
        ---- BEGIN MAP ----
        NAAAAABwAAAAAAAAAAAAAAAAAPAA8AEQAAADYgdXBsYXllciAtIHN0YXJ0EAEAAA
        ACoAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAPgEAAAADAAAAAAABAAAAAAAA
        AAAAAAABAAAAAAAAAAAAANsAAAAAKQAAAAAAAgAAAAAAAAAAAAAAAQAAAAAAAAAA
        AAAiAQAAACoAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAPwEAAAADAAAAAAAB
        AAAAAQAAAAAAAAABAAAAAAAAAAAAANsAAAAAKQAAAAAAAgAAAAEAAAAAAAAAAQAA
        AAAAAAAAAAAiAQAA
        ---- END MAP ----

        # 6 start
        ---- BEGIN MAP ----
        JAAAAABgAAAAgAAAAAAAcAAwAPAA8ABQAAAHN0YXJ0XAAAAAACoAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAPgEAAAAqAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAQAAAA=
        ---- END MAP ----

        # 9 8 uplayer - start2
        ---- BEGIN MAP ----
        OAAAAACQAAAAAAAAAAAAAAAAAPAA8AEgAAADggdXBsYXllciAtIHN0YXJ0Mg==iA
        AAAAACoAAAAAAAIAAAABAAAAAAAAAAEAAAAAAAAAAAAAPgEAAAADAAAAAAADAAAA
        AQAAAAAAAAABAAAAAAAAAAAAANsAAAAAKQAAAAAABAAAAAEAAAAAAAAAAQAAAAAA
        AAAAAAAiAQAA
        ---- END MAP ----

        # 8 start2
        ---- BEGIN MAP ----
        KAAAAACAAAAAoAAAABAAkAAwAPAA8ABgAAAHN0YXJ0Mg==XAAAAAACoAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAPgEAAAAqAAAAAAABAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAEAAAA=
        ---- END MAP ----

        # 11 10 uplayer - doggos cattos
        ---- BEGIN MAP ----
        QAAAAACwAAAAAAAAAAAAAAAAAPAA8AGgAAADEwIHVwbGF5ZXIgLSBkb2dnb3MgY2
        F0dG9ziAAAAAADIAAAAAAAcAAAAGAAAAAAAAAAAAAAAAAAAAAAAAHwAAAAAUAAAA
        AAAHAAAACgAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAEQAAAAAAAwAAAAMAAAAAAAAA
        AQAAAAAAAAAAAAABAAAA
        ---- END MAP ----

        # 10 doggos cattos
        ---- BEGIN MAP ----
        MAAAAACgAAAAAAAAAIAAsAAQAPAA8ADQAAAGRvZ2dvcyBjYXR0b3M=QAEAAAAAIA
        AAAAAAIAAAABAAAAAAAAAAAAAAAAAAAAAAAALAAAAAACAAAAAAAEAAAABAAAAAAA
        AAAAAAAAAAAAAAAAACwAAAAAEQAAAAAAAQAAAAcAAAAAAAAAAAAAAAAAAAAAAAAs
        AAAAAAMAAAAAAAkAAAAHAAAAAAAAAAAAAAAAAAAAAAAASwEAAAARAAAAAAAAAAAA
        BQAAAAAAAAAAAAAAAAAAAAAAACwAAAAAEQAAAAAAAAAAAAoAAAAAAAAAAAAAAAAA
        AAAAAAAsAAAAABEAAAAAAAYAAAACAAAAAAAAAAAAAAAAAAAAAAAAAQAAAA==
        ---- END MAP ----
        """;
}
