using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Tests;

public class WorldDataSerialized
{

    public const string expectedSerialized = """
        # world new [baba] city
        ---- BEGIN WORLD ----
        AQAAAAMADwAAAG5ldyBbYmFiYV0gY2l0eQIAAABWAAAAOwAAAAIAAAAKAAAAFgAA
        AA==
        ---- END WORLD ----

        # 0 autumnregion
        ---- BEGIN REGION ----
        AAABAAAABwAGAAAAYXV0dW1uCgAAAGVkaXRvcnNvbmcMAAAAYXV0dW1ucmVnaW9u
        ---- END REGION ----

        # 1 region 2
        ---- BEGIN REGION ----
        AQAAAAAABgAAAGdhcmRlbgcAAABkZWZhdWx0CAAAAHJlZ2lvbiAy
        ---- END REGION ----

        # 2 new region 2
        ---- BEGIN REGION ----
        AgAAAAAABQAAAHN3YW1wBwAAAGRlZmF1bHQMAAAAbmV3IHJlZ2lvbiAy
        ---- END REGION ----

        # 3 starting region
        ---- BEGIN REGION ----
        AwAAAAAABgAAAGdhcmRlbgcAAABkZWZhdWx0DwAAAHN0YXJ0aW5nIHJlZ2lvbg==
        ---- END REGION ----

        # 2 1 uplayer - start
        ---- BEGIN MAP ----
        OAAAAAAgAAAAAAAAAAAAAAAAAPAA8AEQAAADEgdXBsYXllciAtIHN0YXJ0AA==IA
        EAAAACoAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAEAAAAAAABDAQAAAAMAAAAAAAEA
        AAAAAAAAAQAAAAAAAAAAAAEAAAAAAADeAAAAACkAAAAAAAIAAAAAAAAAAQAAAAAA
        AAAAAAEAAAAAAAAnAQAAACoAAAAAAAAAAAABAAAAAQAAAAAAAAAAAAEAAAAAAABE
        AQAAAAMAAAAAAAEAAAABAAAAAQAAAAAAAAAAAAEAAAAAAADeAAAAACkAAAAAAAIA
        AAABAAAAAQAAAAAAAAAAAAEAAAAAAAAnAQAA
        ---- END MAP ----

        # 1 start
        ---- BEGIN MAP ----
        KAAAAAAQAAAAMAAAAAAAIAAwAPAA8ABQAAAHN0YXJ0AA==YAAAAAACoAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAEAAAAAAABDAQAAACoAAQAAAAEAAAAAAAAAAAAAAAAA
        AAAAAAEAAAAAAAAFAAAA
        ---- END MAP ----

        # 4 3 uplayer - start2
        ---- BEGIN MAP ----
        OAAAAABAAAAAAAAAAAAAAAAAAPAA8AEgAAADMgdXBsYXllciAtIHN0YXJ0MgA=kA
        AAAAACoAAAAAAAIAAAABAAAAAQAAAAAAAAAAAAEAAAAAAABDAQAAAAMAAAAAAAMA
        AAABAAAAAQAAAAAAAAAAAAEAAAAAAADeAAAAACkAAAAAAAQAAAABAAAAAQAAAAAA
        AAAAAAEAAAAAAAAnAQAA
        ---- END MAP ----

        # 3 start2
        ---- BEGIN MAP ----
        KAAAAAAwAAAAUAAAABAAQAAwAPAA8ABgAAAHN0YXJ0MgA=YAAAAAACoAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAEAAAAAAABDAQAAACoAAQAAAAEAAAAAAAAAAAAAAAAA
        AAAAAAEAAAAAAAACAAAA
        ---- END MAP ----

        # 6 5 uplayer - doggos cattos
        ---- BEGIN MAP ----
        QAAAAABgAAAAAAAAAAAAAAAAAPAA8AGQAAADUgdXBsYXllciAtIGRvZ2dvcyBjYX
        R0b3MAkAAAAAADIAAQAAAAcAAAAGAAAAAAAAAAAAAAAAAAEAAAAAAAAgAAAAABQA
        AQAAAAcAAAAKAAAAAAAAAAAAAAAAAAEAAAAAAAAHAAAAABEAAQAAAAMAAAADAAAA
        AQAAAAAAAAAAAAEAAAAAAAACAAAA
        ---- END MAP ----

        # 5 doggos cattos
        ---- BEGIN MAP ----
        MAAAAABQAAAAcAAAADAAYAAQAPAA8ADQAAAGRvZ2dvcyBjYXR0b3MAUAEAAAAAIA
        AQAAAAIAAAABAAAAAAAAAAAAAAAAAAEAAAAAAAAuAAAAAAIABAAAAAQAAAAEAAAA
        AAAAAAAAAAAAAAEAAAAAAAAuAAAAABEAAQAAAAEAAAAHAAAAAAAAAAAAAAAAAAEA
        AAAAAAAuAAAAAAMAAQAAAAkAAAAHAAAAAAAAAAAAAAAAAAEAAAAAAABQAQAAABEA
        AQAAAAAAAAAFAAAAAAAAAAAAAAAAAAEAAAAAAAAuAAAAABEABAAAAAAAAAAKAAAA
        AAAAAAAAAAAAAAEAAAAAAAAuAAAAABEAAQAAAAYAAAACAAAAAAAAAAAAAAAAAAEA
        AAAAAAACAAAA
        ---- END MAP ----

        # 7 single [skull:8] and [algae]
        ---- BEGIN MAP ----
        RAAAAABwAAAAAAAAAFAAAAAgAPAA8AHAAAAHNpbmdsZSBbc2t1bGw6OF0gYW5kIF
        thbGdhZV0AqAEAAAABEABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAB0AAABoZWxv
        bw0KdGhlcmUgW2JhYmFdDQpzc3NsZnNqZIsAAAAAKgABAAAABAAAAAIAAAAAAAAA
        AAAAAAAAAQAAAAAAABEAAAAAKgAEAAAABQAAAAIAAAAAAAAAAAAAAAAAAQAAAAAA
        ABEAAAAAKgAIAAAABAAAAAQAAAAAAAAAAAAAAAAAAQAAAAAAABEAAAAAKgABAAAA
        BgAAAAQAAAAAAAAAAAAAAAAAAQAAAAAAABEAAAAAKgAIAAAABQAAAAQAAAAAAAAA
        AAAAAAAAAQAAAAAAABEAAAAAAgAAAAAACAAAAAYAAAABAAAAAAAAAAAAAQAAAAAA
        AC4AAAAAAgAAAAAACgAAAAYAAAABAAAAAAAAAAAAAQAAAAAAAJoAAAA=
        ---- END MAP ----
        """;
}
